---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: "noderecycler"
    app.kubernetes.io/instance: "{{ .Release.name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "noderecycler"
      app.kubernetes.io/instance: "{{ .Release.name }}"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "noderecycler"
        app.kubernetes.io/instance: "{{ .Release.name }}"
    spec:
      {{- if .Values.rbac.create }}
      serviceAccountName: {{ .Release.Name }}
      {{- end }}
      volumes:
        - name: gce-credentials
          secret:
            secretName: {{ .Values.credentialsSecret }}
      containers:
      - name: noderecycler
        image: {{ .Values.image.name }}:{{ .Values.image.version }}
        volumeMounts:
          - name: gce-credentials
            mountPath: /gce
        env:
        - name: AGE_TO_KILL
          value: "{{ .Values.age_to_kill }}"
        - name: SLEEP_TIME
          value: "{{ .Values.sleep_time }}"
        - name: GCE_CREDENTIALS
          value: "/gce/gce-key.json"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
